# Generated by Django 6.0.6 on 2026-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=100)),
                ('diagnostico', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ESPERA', 'En espera'), ('REPARANDO', 'En reparación'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado')], default='ESPERA', max_length=20)),
                ('solucion', models.TextField(blank=True)),
            ],
        ),
    ]
